var moodStart, genre, aGeneralCharacter, generalCharacter, generalCharacters, characterDescriptions, groupNames, objectives, scene, sceneDescription, theme;

peopleObjectives = [
    "befriend",
    "destroy",
    "kill",
    "take down",
    "save",
    "talk to",
    "nutmeg",
    "roast",
    
];

theme = [
    "survival",
    "cooking",
    "farming",
    "love",
    "death",
    "power",
    "prejudice",
    "hope",
    "war",
    "peace",
    "friendship",
    "revenge",
    "betrayal",
    "forgiveness",
    "crime",
    "punishment",
    "aliens",
    "isolation",
    "chaos",
    "the circle of life",
    "fate",
    "growing up",
    "immortality",
    "technology",
    "totalitarianism",
    "religion",
    "tradition",
    "mental illness",
    "space travel",
    "exploration",
    "greed",
    "justice",
    "patriotism",
    "corruption",
    "exploitation",
    "the end of the world",
    "unfairness",
    "hacking",
    "artificial intelligence",
    "the singularity",
    "robot rights",
    "extraterrestial life",
    "illness",
    "life after death",
    "dancing",
    "singing",
    "bee-keeping",
    "engineering",
    "sewing",
    "fashion",
    "baking",
    "stamp collecting",
    "art",
    "gardening",
    "happiness",
    "sadness",
    "the concept of fun",
    "chivalry",
    "stereotypes",
    "family",
    "relationships",
    "truth",
    "lies",
    "bravery",
    "cowardice",
    "mathematics"
];

sceneDescription = [
    "tiny",
    "microscopic",
    "enormous",
    "spooky",
    "alien",
    "futuristic",
    "ancient",
    "forgotten",
    "mysterious",
    "forbidden",
    "dangerous",
    "holy",
    "bustling",
    "creepy",
    "abandoned",
    "popular",
    "strange-smelling",
    "hypnotic",
    "radioactive",
    "colourful",
    "never-ending",
    "strangely-decorated",
    "tastefully-decorated",
    "rat-infested",
    "lively",
    "vibrant",
    "uninhabited",
    "poorly-decorated",
    "astonishing",
    "critically-acclaimed",
    "beautiful",
    "boring",
    "deadly",
    "grubby",
    "exotic",
    "fabulous",
    "glamorous",
    "gloomy",
    "well-hidden",
    "undiscovered",
    "jolly",
    "luxurious",
    "quaint",
    "quirky",
    "old-fashioned",
    "unfashionable",
    "modern",
    "flying",
    "floating",
    "sinking",
    "burning",
    "mystical",
    "magical",
    "frozen",
    "royal"
];

scene = [
    "city",
    "library",
    "military facility",
    "warehouse", 
    "graveyard", 
    "village", 
    "kingdom", 
    "sewer", 
    "shopping mall", 
    "nightclub", 
    "cave", 
    "labyrinth", 
    "park", 
    "parking lot", 
    "kitchen",
    "planet", 
    "spaceship",
    "moon",
    "star",
    "rainbow",
    "island", 
    "train", 
    "boat", 
    "mountain", 
    "rollercoaster", 
    "street", 
    "motorbike", 
    "bicycle", 
    "shipwreck", 
    "bouncy castle",
    "casino", 
    "library", 
    "junkyard", 
    "basement", 
    "dungeon", 
    "prison", 
    "tavern", 
    "resturant", 
    "cinema", 
    "valley", 
    "mansion", 
    "forest", 
    "jungle", 
    "office", 
    "hotel",
    "an alternate reality", 
    "in outer space", 
    "underwater", 
    "underground", 
    "summer", 
    "winter", 
    "spring", 
    "autumn",
    "your head", 
    "a computer", 
    "a submarine", 
    "a dream", 
    "a nightmare", 
    "a bunker", 
    "a dumpster"
];

characterDescriptions = [
    "tiny",
    "gigantic",
    "lonely",
    "time-travelling",
    "evil",
    "easily-frightened",
    "attractive",
    "short",
    "tall",
    "intimidating",
    "clumsy",
    "good-looking",
    "courageous",
    "anxious",
    "forgetful",
    "famous",
    "shy",
    "scary-looking",
    "one-eyed",
    "bored",
    "ambitious",
    "power-hungry",
    "two-headed",
    "wise",
    "elderly",
    "greedy",
    "invisible",
    "magical",
    "blind",
    "peace-loving",
    "polite",
    "worried",
    "rude",
    "genetically modified",
    "genetically enhanced",
    "grumpy",
    "charming",
    "energetic",
    "imaginary",
    "unfriendly",
    "friendly",
    "nervous",
    "optimistic",
    "pessimistic",
    "undead",
    "quirky",
    "sarcastic",
    "well-dressed",
    "lazy",
    "talkative",
    "royal",
    "cunning",
    "playful",
    "penniless",
    "wealthy",
    "impatient",
    "wind-up",
    "law-abiding",
    "law-breaking",
    "over-enthusiastic"
];

groupNames = [
    "group",
    "faction", 
    "gang", 
    "family", 
    "band", 
    "horde",
    "organization", 
    "league"
];

moodStart = [
    "A unique",
    "A frustrating",
    "A challenging",
    "A rage-inducing",
    "A stressful",
    "A relaxing",
    "A meditative",
    "A calming",
    "A thought-provoking",
    "An addictive",
    "A whimsical",
    "An innovative",
    "An inspiring",
    "A groovey",
    "An artsy",
    "An upbeat",
    "A violent",
    "A peaceful",
    "A dreamy",
    "A stylish",
    "A short-and-sweet",
    "A slow-paced",
    "An intense",
    "A nostalgic",
    "A satirical",
    "A cheerful",
    "A melancholy",
    "A compact"
];

genre = [
    "platformer",
    "puzzle",
    "maze",
    "questing",
    "apocalyptic",
    "beat'em up",
    "battle royale",
    "action rpg",
    "metroidvania",
    "endless runner",
    "shooter",
    "bullet hell",
    "sports",
    "strategy",
    "puzzle",
    "stealth",
    "role-playing",
    "roguelike",
    "survival",
    "horror",
    "card",
    "rhythm",
    "adventure",
    "tower-defense",
    "clicker",
    "hack-and-slash",
    "educational",
    "text-adventure",
    "typing",
    "sandbox",
    "programming",
    "racing",
    "simulation"
];

aGeneralCharacter = [
    "an alien",
    "a monster",
    "a wizard",
    "a witch",
    "an adventurer",
    "an assassin",
    "a sailor",
    "a chef",
    "a robot",
    "a ghost",
    "a human",
    "a skeleton",
    "a snowman",
    "a scientist",
    "a programmer",
    "a student",
    "a youtuber",
    "influencer",
    "a celebrity",
    "a president",
    "a politician",
    "a businessman",
    "an emperor",
    "a ninja",
    "a technophobe",
    "a vampire",
    "a hacker",
    "a zombie",
    "action figure",
    "a geometric shape",
    "a thief",
    "a pirate",
    "a prince",
    "a princess",
    "a king",
    "a queen",
    "a grandfather",
    "a grandmother",
    "a troll",
    "a dwarf",
    "an orc",
    "a goblin",
    "a knight",
    "a farmer",
    "astronaut",
    "a pilot",
    "a chocolatier",
    "archeologist",
    "a doctor",
    "a police officer",
    "a detective",
    "a pyromaniac",
    "a gamer",
    "a tax collector",
    "a plumber",
    "an electrician",
    "a mechanic",
    "a citizen"
    ];

generalCharacter = [
    "alien",
    "monster",
    "wizard",
    "witch",
    "adventurer",
    "assassin",
    "sailor",
    "chef",
    "robot",
    "ghost",
    "human",
    "skeleton",
    "snowman",
    "scientist",
    "programmer",
    "student",
    "youtuber",
    "influencer",
    "celebrity",
    "president",
    "politician",
    "businessman",
    "emperor",
    "ninja",
    "technophobe",
    "vampire",
    "hacker",
    "zombie",
    "action figure",
    "geometric shape",
    "thief",
    "pirate",
    "prince",
    "princess",
    "king",
    "queen",
    "grandfather",
    "grandmother",
    "troll",
    "dwarf",
    "orc",
    "goblin",
    "knight",
    "farmer",
    "astronaut",
    "pilot",
    "chocolatier",
    "archeologist",
    "doctor",
    "police officer",
    "detective",
    "pyromaniac",
    "gamer",
    "tax collector",
    "plumber",
    "electrician",
    "mechanic",
    "citizen"
    ];

generalCharacters = [
    "aliens",
    "monsters",
    "wizards",
    "witches",
    "adventurers",
    "assassins",
    "sailors",
    "chefs",
    "robots",
    "ghosts",
    "humans",
    "skeletons",
    "snowmen",
    "scientists",
    "programmers",
    "students",
    "youtubers",
    "influencers",
    "celebritys",
    "presidents",
    "politicians",
    "businessmen",
    "emperors",
    "ninjas",
    "technophobes",
    "vampires",
    "hackers",
    "zombies",
    "action figures",
    "geometric shapes",
    "thieves",
    "pirates",
    "princes",
    "grandfathers",
    "trolls",
    "dwarves",
    "goblins",
    "knights",
    "farmers",
    "astronauts",
    "pilots",
    "chocolatiers",
    "archeologists",
    "doctors",
    "police officers",
    "detectives",
    "pyromaniacs",
    "gamers",
    "tax collectors",
    "plumbers",
    "electricians",
    "mechanics",
    "citizens"
];
